export default function decorate(block) {
  const fieldNames = [
    'general',
    'layout',
    'themeColor',
    'timerMobileThemeColor',
    'layoutVariation',
    'heightHeroVariation',
    'customSizeTablet',
    'customSizeDesktop',
    'overlayColor',
    'content',
    'eyebrowVariation',
    'eyebrow',
    'eyebrowText',
    'eyebrowDesktopSize',
    'eyebrowTabletSize',
    'eyebrowMobileSize',
    'heading',
    'headingText',
    'headingDesktopSize',
    'headingTabletSize',
    'headingMobileSize',
    'description',
    'legal',
    'desktopFullWidthImageBeginning',
    'desktopFullWidthImageBackgroundAndEnding',
    'tabletFullWidthImageBeginning',
    'tabletFullWidthImageBackgroundAndEnding',
    'mobileFullWidthImageBeginning',
    'mobileFullWidthImageBackgroundAndEnding',
    'mobileImageDisplaysBelowCopy',
    'videoEnable',
    'videoVariation',
    'modalMediaLink',
    'themePlayIcon',
    'ctaDetails',
    'ctaLayout',
    'globalHyperlinks',
    'globalPageOrMediaLink',
    'globalAssetsLinks',
    'globalExternalLinks',
    'globalNoFollow',
    'globalOpenNewWindow',
    'globalAnchorTo',
    'globalAnalyticsTitle',
    'padding',
    'mobilePaddingLeft',
    'mobilePaddingRight',
    'tabletPaddingLeft',
    'tabletPaddingRight',
    'desktopPaddingLeft',
    'desktopPaddingRight',
    'mobilePaddingTop',
    'mobilePaddingBottom',
    'tabletPaddingTop',
    'tabletPaddingBottom',
    'desktopPaddingTop',
    'desktopPaddingBottom',
    'margin',
    'mobileMarginTop',
    'mobileMarginBottom',
    'tabletMarginTop',
    'tabletMarginBottom',
    'desktopMarginTop',
    'desktopMarginBottom',
    'overlay',
    'overlaySection',
    'overlaySectionColor',
    'sectionOverlayPosition',
    'overlaySectionHeading',
    'overlaySectionDescription',
    'overlaySectionLegal',
    'tabletSmallImage',
    'desktopSmallImage',
    'mobileSmallImage',
  ];

  const children = [...block.children];
  const fieldMap = {};
  fieldNames.forEach((name, index) => {
    fieldMap[name] = children[index] || null;
  });

  children.forEach((child, index) => {
    const content = child.textContent?.trim() || '';
    console.log('hero child', {
      index,
      tag: child.tagName,
      content,
    });
  });
}
